### ISSUE TITLE
Comment text is too high

### ISSUE THREAD

**Issue by IAmMoltony** [TheSillyDoggo/Comment-Emojis#1]
After installing the mod, comment text started appearing way higher than it's supposed to.

**Comment by TheSillyDoggo** [comment]
<img width="345" alt="image" src="https://github.com/TheSillyDoggo/Comment-Emojis/assets/95105680/d5e549c1-8efd-4438-b1a0-dcd25f9004ac">
bruh

**Comment by TheSillyDoggo** [comment]
fixed in beta 3 (i think)
